#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
runApplication topoSet
runApplication createPatch -overwrite

restore0Dir
#runApplication setFields

runApplication $(getApplication)

#------------------------------------------------------------------------------
